---
substitutions:
  _MDLINTER: 'markdownlint/markdownlint'
  _BASH: 'bash'
  _ARGBASH: 'matejak/argbash'
  _GIT: 'gcr.io/cloud-builders/git'
  _REPO_URL: 'git@github.com:juanmatias/firestore-backup-helper.git'

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=test-secret > /root/.ssh/id_github' ]
    volumes:
      - name: 'ssh'
        path: /root/.ssh
# Set up git with key and domain
  - name: '${_GIT}'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_github
      cat <<EOF >/root/.ssh/config
      HostName github.com
      IdentityFile /root/.ssh/id_github
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
      ls /root/.ssh/
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  
## merge _HEAD_BRANCH into _BASE_BRANCH
  - name: '${_GIT}'
    id: 'git-clone'
    args:
        - 'clone'
        - '${_REPO_URL}'
        - './repo'
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: '${_GIT}'
    id: 'git-branch'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd ./repo && \
        echo "Setting user" && \
        git config user.email "cloudbuild@${PROJECT_ID}" && git config  user.name "Cloud Run Process ${BUILD_ID}" && \
        echo "Checkout ${_BASE_BRANCH}" && \
        git checkout ${_BASE_BRANCH} && \
        echo "Fetching ${_HEAD_BRANCH}" && \
        git fetch origin ${_HEAD_BRANCH} && \
        echo "Merging" && \
        git merge --no-ff origin/${_HEAD_BRANCH} && \
        echo "Check if we are in ${_MASTER_BRANCH}" && \
        ([ "${_BASE_BRANCH}" = "${_MASTER_BRANCH}" ] && \
         (echo "...working on dev now" && git checkout ${_DEVELOP_BRANCH} && echo "...merging" && git merge --no-ff origin/${_HEAD_BRANCH} && echo "...pushing" && git push origin ${_DEVELOP_BRANCH})) && \
        echo "Pushing ${_BASE_BRANCH}" && \
        git push origin ${_BASE_BRANCH} && \
        echo "Deleting ${_HEAD_BRANCH}" && \
        git push origin --delete ${_HEAD_BRANCH} 

    env:
      - '_HEAD_BRANCH=$_HEAD_BRANCH'
      - '_BASE_BRANCH=$_BASE_BRANCH'
      - '_HEAD_REPO_URL=$_HEAD_REPO_URL'
      - '_PR_NUMBE=$_PR_NUMBE'
    volumes:
    - name: 'ssh'
      path: /root/.ssh
