---
substitutions:
  _MDLINTER: 'markdownlint/markdownlint'
  _BASH: 'bash'

steps:
  # Run unit tests
  - name: '${_MDLINTER}'
    id: 'markdownlinter'
    args:
      - 'README.md'
  - name: '${_BASH}'
    id: 'test'
    args:
      - '-c'
      - |
        echo "Test steps"
  - name: '${_BASH}'
    id: 'build'
    args:
      - '-c'
      - |
        echo "Build steps"
  - name: '${_BASH}'
    id: 'deploy'
    args:
      - '-c'
      - |
        echo "Deploy steps"
