---
substitutions:
  _MDLINTER: 'markdownlint/markdownlint'
  _BASH: 'bash'
  _ARGBASH: 'matejak/argbash'

steps:
  # Run unit tests
  - name: '${_MDLINTER}'
    id: 'markdownlinter'
    args:
      - 'README.md'
